version: '3'

services:
  seek-well:
    build: .
    image: lycantropos/seek-well:latest
    volumes:
      - .:/seek-well/
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command:
      - run
      - -p
      - test_scripts
      - -i
      - init
      - -r
      - refresh
      - -j
      - hierarchy
      - -l
      - fdp
      - -g
      - hierarchy
